module.exports = Object.freeze({
    CUSTOMER_ELIGIBLE: 'CUSTOMER_ELIGIBLE',
    CUSTOMER_INELIGIBLE: 'CUSTOMER_INELIGIBLE',
    TECHNICAL_FAILURE_EXCEPTION: 'TECHNICAL_FAILURE_EXCEPTION',
    INVALID_ACCOUNT_NUMBER_EXCEPTION: 'INVALID_ACCOUNT_NUMBER_EXCEPTION',
    ILLEGAL_ELIGIBILITY_SERVICE_OUTPUT: 'Illegal EligibilityService output',
    SPORTS: 'SPORTS',
    KIDS: 'KIDS',
    MUSIC: 'MUSIC',
    NEWS: 'NEWS',
    MOVIES: 'MOVIES'
});